=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeCRMClient::CustomObjectsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomObjectsApi' do
  before do
    # run before each test
    @api_instance = MergeCRMClient::CustomObjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomObjectsApi' do
    it 'should create an instance of CustomObjectsApi' do
      expect(@api_instance).to be_instance_of(MergeCRMClient::CustomObjectsApi)
    end
  end

  # unit tests for custom_object_classes_custom_objects_create
  # Creates a &#x60;CustomObject&#x60; object with the given values.
  # @param x_account_token Token identifying the end user.
  # @param custom_object_class_id 
  # @param crm_custom_object_endpoint_request 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_debug_mode Whether to include debug fields (such as log file links) in the response.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @return [CRMCustomObjectResponse]
  describe 'custom_object_classes_custom_objects_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for custom_object_classes_custom_objects_list
  # Returns a list of &#x60;CustomObject&#x60; objects.
  # @param x_account_token Token identifying the end user.
  # @param custom_object_class_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :created_after If provided, will only return objects created after this datetime.
  # @option opts [Time] :created_before If provided, will only return objects created before this datetime.
  # @option opts [String] :cursor The pagination cursor value.
  # @option opts [Boolean] :include_deleted_data Whether to include data that was marked as deleted by third party webhooks.
  # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
  # @option opts [Boolean] :include_remote_fields Whether to include all remote fields, including fields that Merge did not map to common models, in a normalized format.
  # @option opts [Time] :modified_after If provided, only objects synced by Merge after this date time will be returned.
  # @option opts [Time] :modified_before If provided, only objects synced by Merge before this date time will be returned.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
  # @return [PaginatedCustomObjectList]
  describe 'custom_object_classes_custom_objects_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for custom_object_classes_custom_objects_meta_patch_retrieve
  # Returns metadata for &#x60;CRMCustomObject&#x60; PATCHs.
  # @param x_account_token Token identifying the end user.
  # @param custom_object_class_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MetaResponse]
  describe 'custom_object_classes_custom_objects_meta_patch_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for custom_object_classes_custom_objects_meta_post_retrieve
  # Returns metadata for &#x60;CRMCustomObject&#x60; POSTs.
  # @param x_account_token Token identifying the end user.
  # @param custom_object_class_id 
  # @param [Hash] opts the optional parameters
  # @return [MetaResponse]
  describe 'custom_object_classes_custom_objects_meta_post_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for custom_object_classes_custom_objects_partial_update
  # Updates a &#x60;CustomObject&#x60; object with the given &#x60;id&#x60;.
  # @param x_account_token Token identifying the end user.
  # @param custom_object_class_id 
  # @param id 
  # @param patched_crm_custom_object_endpoint_request 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_debug_mode Whether to include debug fields (such as log file links) in the response.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @return [CRMCustomObjectResponse]
  describe 'custom_object_classes_custom_objects_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for custom_object_classes_custom_objects_retrieve
  # Returns a &#x60;CustomObject&#x60; object with the given &#x60;id&#x60;.
  # @param x_account_token Token identifying the end user.
  # @param custom_object_class_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
  # @option opts [Boolean] :include_remote_fields Whether to include all remote fields, including fields that Merge did not map to common models, in a normalized format.
  # @return [CustomObject]
  describe 'custom_object_classes_custom_objects_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
