=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MergeCRMClient::OpportunitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OpportunitiesApi' do
  before do
    # run before each test
    @api_instance = MergeCRMClient::OpportunitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OpportunitiesApi' do
    it 'should create an instance of OpportunitiesApi' do
      expect(@api_instance).to be_instance_of(MergeCRMClient::OpportunitiesApi)
    end
  end

  # unit tests for opportunities_create
  # Creates an &#x60;Opportunity&#x60; object with the given values.
  # @param x_account_token Token identifying the end user.
  # @param opportunity_endpoint_request 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_debug_mode Whether to include debug fields (such as log file links) in the response.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @return [OpportunityResponse]
  describe 'opportunities_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for opportunities_list
  # Returns a list of &#x60;Opportunity&#x60; objects.
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id If provided, will only return opportunities with this account.
  # @option opts [Time] :created_after If provided, will only return objects created after this datetime.
  # @option opts [Time] :created_before If provided, will only return objects created before this datetime.
  # @option opts [String] :cursor The pagination cursor value.
  # @option opts [String] :expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
  # @option opts [Boolean] :include_deleted_data Whether to include data that was marked as deleted by third party webhooks.
  # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
  # @option opts [Time] :modified_after If provided, will only return objects modified after this datetime.
  # @option opts [Time] :modified_before If provided, will only return objects modified before this datetime.
  # @option opts [String] :owner_id If provided, will only return opportunities with this owner.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :remote_fields Which fields should be returned in non-normalized form.
  # @option opts [String] :remote_id The API provider&#39;s ID for the given object.
  # @option opts [String] :stage_id If provided, will only return opportunities with this stage.
  # @option opts [String] :status If provided, will only return opportunities with this status. Options: (&#39;OPEN&#39;, &#39;WON&#39;, &#39;LOST&#39;)
  # @return [PaginatedOpportunityList]
  describe 'opportunities_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for opportunities_meta_patch_retrieve
  # Returns metadata for &#x60;Opportunity&#x60; PATCHs.
  # @param x_account_token Token identifying the end user.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MetaResponse]
  describe 'opportunities_meta_patch_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for opportunities_meta_post_retrieve
  # Returns metadata for &#x60;Opportunity&#x60; POSTs.
  # @param x_account_token Token identifying the end user.
  # @param [Hash] opts the optional parameters
  # @return [MetaResponse]
  describe 'opportunities_meta_post_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for opportunities_partial_update
  # @param x_account_token Token identifying the end user.
  # @param id 
  # @param patched_opportunity_endpoint_request 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_debug_mode Whether to include debug fields (such as log file links) in the response.
  # @option opts [Boolean] :run_async Whether or not third-party updates should be run asynchronously.
  # @return [OpportunityResponse]
  describe 'opportunities_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for opportunities_retrieve
  # Returns an &#x60;Opportunity&#x60; object with the given &#x60;id&#x60;.
  # @param x_account_token Token identifying the end user.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
  # @option opts [Boolean] :include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models.
  # @option opts [String] :remote_fields Which fields should be returned in non-normalized form.
  # @return [Opportunity]
  describe 'opportunities_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
