=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeCRMClient::FieldTypeEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeCRMClient::FieldTypeEnum do
  let(:instance) { MergeCRMClient::FieldTypeEnum.new }

  describe 'test an instance of FieldTypeEnum' do
    it 'should create an instance of FieldTypeEnum' do
      expect(instance).to be_instance_of(MergeCRMClient::FieldTypeEnum)
    end
  end
end
