=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeCRMClient::IssueStatusEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeCRMClient::IssueStatusEnum do
  let(:instance) { MergeCRMClient::IssueStatusEnum.new }

  describe 'test an instance of IssueStatusEnum' do
    it 'should create an instance of IssueStatusEnum' do
      expect(instance).to be_instance_of(MergeCRMClient::IssueStatusEnum)
    end

    it 'should allow dynamic value on deserialize helper' do
      deserialized = MergeCRMClient::IssueStatusEnum.build_from_hash("DYNAMIC")

      expect(deserialized.value).to be(MergeCRMClient::IssueStatusEnum::MERGE_NONSTANDARD_VALUE)
      expect(deserialized.raw_value).to eq("DYNAMIC")
    end
  end
end
