=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeCRMClient::OriginTypeEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeCRMClient::OriginTypeEnum do
  let(:instance) { MergeCRMClient::OriginTypeEnum.new }

  describe 'test an instance of OriginTypeEnum' do
    it 'should create an instance of OriginTypeEnum' do
      expect(instance).to be_instance_of(MergeCRMClient::OriginTypeEnum)
    end
  end
end
