=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MergeCRMClient::PatchedEngagementEndpointRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MergeCRMClient::PatchedEngagementEndpointRequest do
  let(:instance) { MergeCRMClient::PatchedEngagementEndpointRequest.new }

  describe 'test an instance of PatchedEngagementEndpointRequest' do
    it 'should create an instance of PatchedEngagementEndpointRequest' do
      expect(instance).to be_instance_of(MergeCRMClient::PatchedEngagementEndpointRequest)
    end
  end
  describe 'test attribute "model"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
