=begin
#Merge CRM API

#The unified API for building rich integrations with multiple CRM platforms.

The version of the OpenAPI document: 1.0
Contact: hello@merge.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module MergeCRMClient
  class AssociationTypeRequestRequest
    attr_accessor :source_object_class

    attr_accessor :target_object_classes

    attr_accessor :remote_key_name

    attr_accessor :display_name

    attr_accessor :cardinality

    attr_accessor :is_required

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'source_object_class' => :'source_object_class',
        :'target_object_classes' => :'target_object_classes',
        :'remote_key_name' => :'remote_key_name',
        :'display_name' => :'display_name',
        :'cardinality' => :'cardinality',
        :'is_required' => :'is_required'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'source_object_class' => :'ObjectClassDescriptionRequest',
        :'target_object_classes' => :'Array<ObjectClassDescriptionRequest>',
        :'remote_key_name' => :'String',
        :'display_name' => :'String',
        :'cardinality' => :'CardinalityEnum',
        :'is_required' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MergeCRMClient::AssociationTypeRequestRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MergeCRMClient::AssociationTypeRequestRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'source_object_class')
        self.source_object_class = attributes[:'source_object_class']
      end

      if attributes.key?(:'target_object_classes')
        if (value = attributes[:'target_object_classes']).is_a?(Array)
          self.target_object_classes = value
        end
      end

      if attributes.key?(:'remote_key_name')
        self.remote_key_name = attributes[:'remote_key_name']
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'cardinality')
        self.cardinality = attributes[:'cardinality']
      end

      if attributes.key?(:'is_required')
        self.is_required = attributes[:'is_required']
      else
        self.is_required = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @source_object_class.nil?
        invalid_properties.push('invalid value for "source_object_class", source_object_class cannot be nil.')
      end

      if @target_object_classes.nil?
        invalid_properties.push('invalid value for "target_object_classes", target_object_classes cannot be nil.')
      end

      if @remote_key_name.nil?
        invalid_properties.push('invalid value for "remote_key_name", remote_key_name cannot be nil.')
      end

      if @remote_key_name.to_s.length < 1
        invalid_properties.push('invalid value for "remote_key_name", the character length must be great than or equal to 1.')
      end

      if !@display_name.nil? && @display_name.to_s.length < 1
        invalid_properties.push('invalid value for "display_name", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @source_object_class.nil?
      return false if @target_object_classes.nil?
      return false if @remote_key_name.nil?
      return false if @remote_key_name.to_s.length < 1
      return false if !@display_name.nil? && @display_name.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] remote_key_name Value to be assigned
    def remote_key_name=(remote_key_name)
      if remote_key_name.nil?
        fail ArgumentError, 'remote_key_name cannot be nil'
      end

      if remote_key_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "remote_key_name", the character length must be great than or equal to 1.'
      end

      @remote_key_name = remote_key_name
    end

    # Custom attribute writer method with validation
    # @param [Object] display_name Value to be assigned
    def display_name=(display_name)
      if !display_name.nil? && display_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "display_name", the character length must be great than or equal to 1.'
      end

      @display_name = display_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          source_object_class == o.source_object_class &&
          target_object_classes == o.target_object_classes &&
          remote_key_name == o.remote_key_name &&
          display_name == o.display_name &&
          cardinality == o.cardinality &&
          is_required == o.is_required
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [source_object_class, target_object_classes, remote_key_name, display_name, cardinality, is_required].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MergeCRMClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
